### PR TITLE
Update React dependency to use looser SemVer; Add type definition for any typescript users.

### PR DESCRIPTION
**Pull request by rozzzly**
I noticed that my webpack app's bundles were suddenly huge. Upon investigation, I found that this package was forcing webpack to include a second version of react because [it had a dependency on `~0.14.0`](https://github.com/mattzeunert/react-with-context/commit/8b1f1363cea1e54e0b6c566eea41842553b84cfe#commitcomment-20951904) It's probably best to use a carret range on this semver seeing as this is a small package, unlikely to change. 

Also, I included a typescript definition file (`WithContext.d.ts`). If you're not familiar with them, it just lets consumers of the package who use typescript to get autocompletion and type checking. This will not affect how the package functions in the slightest. However, depending on their IDE, even developers who do not use typescript--just pure js--can get the benefits type definitions provide.

#### Don't merge this right away.
The `package.json` is setup for my fork of the package, `react-wrap-with-context`. If you're cool with the changes, let me know and I'll update this pr to make make the package name, author, and repository url, etc in `package.json` reflect the original package. Currently it's setup for my temporary `react-wrap-with-context` package. After you merge in the updated version and publish to npm, I'll remove my repository and package.

### CODE REVIEW

**Comment by mattzeunert** [comment]
This looks good. Thanks for taking the time to making all those fixes!

I'll merge after you've made those changes.

**Comment by rozzzly** [comment]
Okay. Ready to go!

Thanks for the quick response

**Comment by mattzeunert** [comment]
Thanks! 👍

**Comment by mattzeunert** [comment]
Just pushed to NPM.

**Pull request merged**
